import { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";
// import styles from "./index.module.css";

function Books() {
  const { subject } = useParams();
  const [counter, setCounter] = useState(1);

  useEffect(() => {
    // getBooks();
  }, []);

  const getBooks = async () => {
    const url = `https://openlibrary.org/subjects/${subject}.json?limit=10?offset=${counter}`;
    axios.get(url).then(res => console.log("respose", JSON.stringify(res))).catch(err => console.log("err", JSON.stringify(err.message)));
  }

  const booksData = [
    {
      key: "/works/OL53919W",
      title: "The Adventures of Tom Sawyer",
      edition_count: 827,
      cover_id: 7103517,
      cover_edition_key: "OL23269295M",
      subject: [
        "The Adventures of Tom Sawyer",
        "Mark Twain",
        "1835-1910",
        "19th Century",
        "Historical",
        "Fiction",
        "Classic",
        "American",
        "Novel",
        "Children",
        "Children's",
        "Kid's",
        "Juvenile",
        "Young Adult",
        "ADULT",
        "1967 Lewis Carroll Shelf Award",
        "Literature",
        "Hardcover",
        "Paperback",
        "Kindle",
        "E-book",
        "Free online",
        "Dummies (Bookselling)",
        "Manuscripts",
        "American Manuscripts",
        "Movies",
        "Theatre",
        "Theater",
        "Adventure stories",
        "Novels, other prose & writers: 19th century",
        "Male friendship",
        "Adventure",
        "Adventures",
        "Adventurerers",
        "Stories",
        "Books",
        "Readers",
        "Runaway children",
        "Child witnesses",
        "Fugitive slaves",
        "Race relations",
        "Boys",
        "Readers for new literates",
        "High interest-low vocabulary books",
        "open_syllabus_project",
        "Sawyer, Tom (Personaje literario)",
        "Relatos de aventura",
        "Muchachos",
        "Cartoons and comics",
        "History",
        "Social life and customs",
        "Niños",
        "Translations",
        "Russian",
        "Spanish",
        "Polish",
        "Czech",
        "Ficción juvenil",
        "Juvenile fiction",
        "Klassenlektüre",
        "Englischunterricht",
        "Translations into Czech",
        "Children's stories, American",
        "Tom Sawyer (Fictitious character)",
        "Children's fiction",
        "Mississippi river, fiction",
        "Missouri, fiction",
        "Adventure and adventurers, fiction",
        "Sawyer, tom (fictitious character), fiction",
        "American fiction (fictional works by one author)",
        "Fiction, action & adventure",
        "Fiction, humorous",
        "Mississippi, fiction",
        "Slaves, fiction",
        "Southern states, fiction",
        "Comics & graphic novels, literary",
        "Fiction, general",
        "Suo xie ben",
        "Er tong wen xue",
        "Chang pian xiao shuo",
        "Huckleberry Finn (Fictitious character)",
        "Adventure fiction",
        "Adventure and adventurers",
        "Graphic novels",
        "Comic books, strips",
        "Facsimiles",
        "Specimens",
        "Large type books",
        "American Adventure stories",
        "History and criticism",
        "Manners and customs",
        "Runaways",
        "Adaptations",
        "Witnesses",
        "Runaways, fiction",
        "American literature",
        "FICTION / Classics",
        "FICTION / Literary",
        "Aventures et aventuriers",
        "Romans",
        "Orphelins",
        "Children's stories",
        "Conduct of life",
        "Abenteuer",
        "Waisenkind",
        "Ouvrages de fiction",
        "FICTION / Action & Adventure",
        "Boys, fiction",
        "Fiction, humorous, general",
        "Humorous stories",
        "Behavior, fiction",
        "Literature and fiction, juvenile",
        "Friendship, fiction",
        "Literature, collections",
        "AR 8.3.",
        "Spanish language materials",
        "Sawyer, Tom (Personaje imaginario)",
        "Novela",
        "Novela de acción y aventura",
        "Novela humorística",
        "Novela estadounidense",
        "Garçons",
        "Romans, nouvelles, etc. pour la jeunesse",
        "Tom Sawyer (Fictional character)",
        "English language, textbooks for foreign speakers",
      ],
      ia_collection: [
        "_locker-hank_b",
        "additional_collections",
        "americana",
        "americanuniversity-ol",
        "audio_bookspoetry",
        "bannedbooks",
        "bell",
        "bell_literature",
        "belmont-ol",
        "blc",
        "bostonpubliclibrary",
        "bostonuniversitylibraries-ol",
        "bpljordan-ol",
        "cdl",
        "china",
        "cnusd-ol",
        "community",
        "cornell",
        "cua-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "framingham-ol",
        "goffstownlibrary-ol",
        "gutenberg",
        "gwulibraries-ol",
        "hamiltonpubliclibrary-ol",
        "iacl",
        "inlibrary",
        "internetarchivebooks",
        "ithacacollege-ol",
        "johnshopkins-ol",
        "library_of_atlantis",
        "library_of_congress",
        "librarygenesis",
        "librivoxaudio",
        "marygrovecollege",
        "marymount-ol",
        "microfilm",
        "nationalyiddishbookcenter",
        "newyorkpubliclibrary",
        "occidentalcollegelibrary-ol",
        "openlibrary-d-ol",
        "opensource",
        "popularchinesebooks",
        "printdisabled",
        "randolph-macon-college-ol",
        "robarts",
        "rochester-ol",
        "spokanepubliclibrary-ol",
        "stmaryscountylibrary",
        "the-claremont-colleges-ol",
        "thomasfisher",
        "thomasfishercanadiana",
        "toronto",
        "trent_university",
        "tulsacc-ol",
        "ualbertawiedrick",
        "uconn_libraries",
        "unb-ol",
        "uni-ol",
        "university_of_alberta_libraries",
        "university_of_alberta_libraries_microfilm",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "universityofthewest-ol",
        "wilsoncollege-ol",
        "worthingtonlibraries-ol",
        "yrlsc",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL25098005M",
      lending_identifier: "cihm_93635",
      authors: [
        {
          key: "/authors/OL18319A",
          name: "Mark Twain",
        },
      ],
      first_publish_year: 1817,
      ia: "cihm_93635",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "cihm_93635",
        isbn: "0665936354",
        oclc: null,
        openlibrary_work: "OL53919W",
        openlibrary_edition: "OL25098005M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL7574091W",
      title: "[William Wheeler Hubbell, authorized to apply for patents.]",
      edition_count: 241,
      cover_id: 10200621,
      cover_edition_key: null,
      subject: [
        "Administration of Justice",
        "Agricultural machinery",
        "Ammunition",
        "Animal feeding",
        "Appropriations and expenditures",
        "Armed Forces",
        "Artillery",
        "Authority",
        "Books",
        "Building materials",
        "Carriages and carts",
        "Cartridges",
        "Cemeteries",
        "Chemical industry",
        "Chemistry",
        "Children",
        "Claims",
        "Clothing trade",
        "Commercial law",
        "Concrete Pavements",
        "Copyright",
        "Corn",
        "Cotton",
        "Engines",
        "Family",
        "Field and mountain Artillery",
        "Fire prevention",
        "Firearms",
        "Fires",
        "Floor coverings",
        "Fruit trade",
        "Glass",
        "Governmental investigations",
        "Hardware industry",
        "Horses",
        "International law",
        "Inventions",
        "Jurisdiction",
        "Kerosene",
        "Lighting",
        "Locks and keys",
        "Machine-tool industry",
        "Machinery",
        "Machinery industry",
        "Manufactures",
        "Metal trade",
        "Metals",
        "Metered mail",
        "Military railroads",
        "Military supplies",
        "Military weapons",
        "Officials and employees",
        "Packaging",
        "Paper products",
        "Patent offices",
        "Patents",
        "Petitions",
        "Petroleum",
        "Plumbing",
        "Postal service",
        "Printing",
        "Private Bills",
        "Railroads",
        "Revenue",
        "Revenue stamps",
        "Rifles",
        "Rubber",
        "Science",
        "Sewing machines",
        "Ships",
        "Shoe industry",
        "Shoe machinery industry",
        "Signals and signaling",
        "Springs (Mechanism)",
        "Steam-boilers",
        "Steam-engines",
        "Study and teaching",
        "Submarine Cables",
        "Sugar trade",
        "Telegraph",
        "Telephone",
        "Textile fabrics",
        "Tobacco",
        "Tobacco industry",
        "Trademarks",
        "Transportation",
        "Union Metallic Cartridge Company",
        "United States",
        "United States. Congress",
        "United States. Court of Claims",
        "United States. War Dept",
        "Wages",
        "Weapons",
        "Widows",
        "Wills",
      ],
      ia_collection: [""],
      lendinglibrary: false,
      printdisabled: false,
      lending_edition: "",
      lending_identifier: "",
      authors: [
        {
          key: "/authors/OL2319898A",
          name: "United States. Congress. Senate. Committee on Patents",
        },
      ],
      first_publish_year: 1858,
      ia: null,
      public_scan: false,
      has_fulltext: false,
    },
    {
      key: "/works/OL258301W",
      title: "Доктор Живаго",
      edition_count: 174,
      cover_id: 1045432,
      cover_edition_key: "OL9058491M",
      subject: [
        "Fiction",
        "History",
        "Continental european fiction (fictional works by one author)",
        "Fiction, historical, general",
        "Soviet union, history, revolution, 1917-1921, fiction",
        "958",
        "Prohibited book",
        "Politics",
        "Soviet Union",
        "Revolution",
        "1917-1921",
        "Historical",
        "Classic",
        "Literature",
        "Books",
        "Novels",
        "Hardcovers",
        "Paperbacks",
        "e-books",
        "audio-books",
        "Movie tie-in",
        "Russian propoganda",
        "Love stories",
        "Russian poetry",
        "Translations into English",
        "Physicians",
        "War stories",
        "Russian Poets",
        "Political fiction",
        "Historical fiction",
        "Epic literature",
        "Didactic fiction",
        "World war, 1914-1918",
        "Revolution (Russia : 1905-1907) fast (OCoLC)fst01354573",
        "Romance fiction",
        "Russian fiction",
        "Fiction, political",
        "Soviet union, fiction",
        "Children's fiction",
        "Readers",
        "Soviet union, history, fiction",
        "English language",
        "Study and teaching",
        "Foreign speakers",
        "Readers for new literates",
        "freedom",
        "Moscow",
        "Romance",
        "Czar Nicholas II",
        "WWI",
        "Russian Revolution",
        "Russian Psychological fiction",
        "Fiction, historical",
        "Long Now Manual for Civilization",
        "Translations into Chinese",
        "Romans, nouvelles",
        "Histoire",
        "Roman russe",
        "Littérature",
        "Russian literature",
        "Littérature russe",
      ],
      ia_collection: [
        "ambslibrary-ol",
        "americana",
        "binghamton-ol",
        "china",
        "cnusd-ol",
        "delawarecountydistrictlibrary",
        "framingham-ol",
        "goffstownlibrary-ol",
        "gwulibraries-ol",
        "inlibrary",
        "internetarchivebooks",
        "johnshopkins-ol",
        "library_of_atlantis",
        "librarygenesis",
        "marygrovecollege",
        "miltonpubliclibrary-ol",
        "openlibrary-d-ol",
        "popularchinesebooks",
        "printdisabled",
        "randolph-macon-college-ol",
        "salisburyfreelibrary-ol",
        "stmaryscountylibrary",
        "the-claremont-colleges-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "worthingtonlibraries-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL39804749M",
      lending_identifier: "doctorzhivago0000bori_y9y8",
      authors: [
        {
          key: "/authors/OL41878A",
          name: "Boris Leonidovich Pasternak",
        },
        {
          key: "/authors/OL9692213A",
          name: "B. Pasternak",
        },
      ],
      first_publish_year: 1957,
      ia: "doctorzhivago0000bori_y9y8",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "doctorzhivago0000bori_y9y8",
        isbn: "9780394422237",
        oclc: null,
        openlibrary_work: "OL258301W",
        openlibrary_edition: "OL39804749M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL45809W",
      title: "James and the Giant Peach",
      edition_count: 144,
      cover_id: 8231813,
      cover_edition_key: "OL24211251M",
      subject: [
        "Christian Books",
        "Roald Dahl",
        "children",
        "Children's",
        "Kid's",
        "Tweens",
        "Adolescent",
        "Juvenile",
        "Fiction",
        "Literature",
        "Stories",
        "Fantasy",
        "Fairy tales",
        "Make",
        "Believe",
        "Books",
        "Readers",
        "Chapters",
        "Chapter books",
        "Humor",
        "Humorous",
        "Bugs",
        "Ants",
        "Insects",
        "Peaches",
        "Magic",
        "Crystals",
        "Family",
        "Boys",
        "Mean",
        "Aunts",
        "Lonely",
        "Loneliness",
        "Open Library Staff Picks",
        "Translations",
        "Spanish",
        "German",
        "Cuentos de hadas",
        "Humorous stories",
        "Children's stories",
        "Juvenile fiction",
        "Orphans",
        "Peach",
        "Children's fiction",
        "Fantasy fiction",
        "Translations into Spanish",
        "English fiction",
        "Children's plays",
        "Plays",
        "Imagination",
        "Children's literature",
        "Size and shape, fiction",
      ],
      ia_collection: [
        "California-State-Suggested-Reading",
        "additional_collections",
        "album_recordings",
        "americana",
        "audio_music",
        "bannedbooks",
        "barryuniversity-ol",
        "belmont-ol",
        "books",
        "bpljordan-ol",
        "brynmawr-ol",
        "china",
        "cnusd-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "denverpubliclibrary-ol",
        "framingham-ol",
        "goffstownlibrary-ol",
        "hamiltonpubliclibrary-ol",
        "inlibrary",
        "internetarchivebooks",
        "ithacacollege-ol",
        "library_of_atlantis",
        "librarygenesis",
        "marygrovecollege",
        "miltonpubliclibrary-ol",
        "openlibrary-d-ol",
        "popularchinesebooks",
        "printdisabled",
        "salisburyfreelibrary-ol",
        "samples_only",
        "stmaryscountylibrary",
        "tulsacc-ol",
        "uni-ol",
        "universityofarizona-ol",
        "universityofoklahoma-ol",
        "vinyl_bostonpubliclibrary",
        "worthingtonlibraries-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL7465014M",
      lending_identifier: "jamesgiantpeach00roal",
      authors: [
        {
          key: "/authors/OL34184A",
          name: "Roald Dahl",
        },
      ],
      first_publish_year: 1961,
      ia: "jamesgiantpeach00roal",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: true,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "jamesgiantpeach00roal",
        isbn: "0394912829",
        oclc: null,
        openlibrary_work: "OL45809W",
        openlibrary_edition: "OL7465014M",
        last_loan_date: "2020-09-09T03:57:13Z",
        num_waitlist: "0",
        last_waitlist_date: "2020-09-02T04:02:35Z",
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL45885W",
      title: "The BFG",
      edition_count: 130,
      cover_id: 6386103,
      cover_edition_key: "OL24201604M",
      subject: [
        "Open Library Staff Picks",
        "Roald Dahl",
        "Tweens",
        "Teens",
        "Teenagers",
        "YA",
        "Young adult",
        "Juvenile",
        "Fiction",
        "Fantasy",
        "Make-believe",
        "Literature",
        "Chapters",
        "Chapter Book",
        "Books",
        "Story",
        "Stories",
        "Humor",
        "Funny",
        "Adventure",
        "Friendly",
        "Giants",
        "Orphans",
        "Kidnapping",
        "Dreamcatcher",
        "Children's fiction",
        "Giants, fiction",
        "Orphans, fiction",
        "Humorous stories",
        "Juvenile works",
        "Children's stories",
        "Juvenile fiction",
        "Magie",
        "Humour",
        "Friendship",
        "Rescues",
        "Translations into Chinese",
        "Tong hua",
        "Tales",
        "Literature and fiction, juvenile",
        "Reuzen",
        "Jeugdboeken ; verhalen",
        "Children's stories, English",
        "nyt:childrens-middle-grade-paperback=2016-06-26",
        "New York Times bestseller",
        "Gigante",
        "Novela juvenil",
        "Huéfanos",
        "Bien y mal",
        "Fantasy & Magic",
        "Spanish language materials",
        "Child and youth fiction",
      ],
      ia_collection: [
        "americana",
        "barryuniversity-ol",
        "belmont-ol",
        "bostonuniversitylibraries-ol",
        "bpljordan-ol",
        "china",
        "cnusd-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "denverpubliclibrary-ol",
        "framingham-ol",
        "goffstownlibrary-ol",
        "inlibrary",
        "internetarchivebooks",
        "ithacacollege-ol",
        "library_of_atlantis",
        "librarygenesis",
        "marymount-ol",
        "miltonpubliclibrary-ol",
        "openlibrary-d-ol",
        "phillipsacademy-preview",
        "popularchinesebooks",
        "printdisabled",
        "salisburyfreelibrary-ol",
        "spokanepubliclibrary-ol",
        "stmaryscountylibrary",
        "unb-ol",
        "uni-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "worthingtonlibraries-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL9524566M",
      lending_identifier: "lebongrosgeantle0000dahl",
      authors: [
        {
          key: "/authors/OL34184A",
          name: "Roald Dahl",
        },
      ],
      first_publish_year: 1982,
      ia: "lebongrosgeantle0000dahl",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "lebongrosgeantle0000dahl",
        isbn: "2070336026",
        oclc: null,
        openlibrary_work: "OL45885W",
        openlibrary_edition: "OL9524566M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL15854658W",
      title: "Black Beauty",
      edition_count: 107,
      cover_id: 5007492,
      cover_edition_key: "OL9730766M",
      subject: [
        "Black Beauty",
        "Anna Sewell",
        "Original publication 1877",
        "19th Century",
        "Children",
        "Children's",
        "Kids",
        "Juvenile",
        "Classic",
        "Fiction",
        "Books",
        "Stories",
        "Drama",
        "Biography",
        "History",
        "Legends",
        "Animals",
        "Classic Literature",
        "Juvenile Literature",
        "Animals - Horses",
        "Horses",
        "Animal rights",
        "Humane treatment",
        "Kindness",
        "Gentleness",
        "Goodness & cruelty",
        "Morals",
        "Morality",
        "Children's fiction",
        "Horses, fiction",
        "England, fiction",
        "Animals, treatment, fiction",
        "Juvenile fiction",
        "Folklore",
        "Specimens",
        "Toy and movable books",
        "Juvenile sound recordings",
        "Black Beauty (Fictitious character)",
        "High interest-low vocabulary books",
        "Easy reading materials",
        "Child and youth fiction",
        "Fiction, historical",
        "Great britain, fiction",
        "Readers",
        "Fairy tales",
        "Adventure and adventurers, fiction",
        "Fiction, romance, general",
        "Adaptations",
        "Comic books, strips",
        "Graphic novels",
        "Animal welfare",
        "Social conditions",
        "Treatment",
        "Literature and fiction, juvenile",
        "Chevaux",
        "Romans, nouvelles, etc. pour la jeunesse",
      ],
      ia_collection: [
        "americana",
        "barryuniversity-ol",
        "blc",
        "bostonuniversitylibraries-ol",
        "bpljordan-ol",
        "brynmawr-ol",
        "cdl",
        "china",
        "cnusd-ol",
        "delawarecountydistrictlibrary",
        "iacl",
        "inlibrary",
        "internetarchivebooks",
        "library_of_atlantis",
        "openlibrary-d-ol",
        "printdisabled",
        "stmaryscountylibrary",
        "unb-ol",
        "websterfamilyvetmed",
        "yrlsc",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL7242604M",
      lending_identifier: "blackbeautyhisgr00seweiala",
      authors: [
        {
          key: "/authors/OL25123A",
          name: "Anna Sewell",
        },
      ],
      first_publish_year: 1877,
      ia: "blackbeautyhisgr00seweiala",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "blackbeautyhisgr00seweiala",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL40252W",
        openlibrary_edition: "OL7242604M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL482894W",
      title: "The Bridge of San Luis Rey",
      edition_count: 95,
      cover_id: 40577,
      cover_edition_key: "OL349149M",
      subject: [
        "Accident victims",
        "Accidents",
        "American fiction",
        "Bridges",
        "Fiction",
        "History",
        "Pulitzer Prize Winner",
        "Russian language",
        "Text",
        "Translations into Spanish",
        "award:pulitzer_prize=1928",
        "award:pulitzer_prize=fiction",
        "18.06 Anglo-American literature",
        "American fiction (fictional works by one author)",
        "Fiction, historical",
        "Peru, fiction",
        "Large type books",
        "Fiction, historical, general",
        "Social life and customs",
        "Manners and customs",
        "Thornton Wilder",
        "Pulitzer Prize",
        "Winner",
        "Historical",
        "American",
        "Adult",
        "Classic",
        "Literature",
        "Stories",
        "Story",
        "Book",
        "Books",
        "Religion",
        "Religious",
        "Tragedy",
        "Tragedies",
        "Death",
        "Fate",
        "Divine",
        "Intervention",
      ],
      ia_collection: [
        "americana",
        "binghamton-ol",
        "cnusd-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "drakeuniversity-ol",
        "goffstownlibrary-ol",
        "gwulibraries-ol",
        "inlibrary",
        "internetarchivebooks",
        "library_of_atlantis",
        "marygrovecollege",
        "miltonpubliclibrary-ol",
        "openlibrary-d-ol",
        "printdisabled",
        "randolph-macon-college-ol",
        "riceuniversity-ol",
        "rochester-ol",
        "spokanepubliclibrary-ol",
        "stmaryscountylibrary",
        "trent_university",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL32977482M",
      lending_identifier: "bridgeofsanluisr0000wild",
      authors: [
        {
          key: "/authors/OL30224A",
          name: "Thornton Wilder",
        },
        {
          key: "/authors/OL3893204A",
          name: "T. Wilder",
        },
        {
          key: "/authors/OL7943030A",
          name: "Thornton Wilder",
        },
        {
          key: "/authors/OL9309606A",
          name: "Wilder T.",
        },
      ],
      first_publish_year: 1927,
      ia: "bridgeofsanluisr0000wild",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "bridgeofsanluisr0000wild",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL20288774W",
        openlibrary_edition: "OL32977482M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL4072567W",
      title: "The Bobbsey Twins",
      edition_count: 94,
      cover_id: 9330264,
      cover_edition_key: "OL27578672M",
      subject: [
        "Laura Lee Hope",
        "Bobbsey Twins",
        "Series",
        "Fiction",
        "Children",
        "Children's",
        "Kid's",
        "Youngsters",
        "Tweens",
        "Young adult",
        "Juvenile",
        "Classic",
        "Literature",
        "Book",
        "Books",
        "Chapters",
        "Family",
        "Siblings",
        "Twins",
        "2 sets",
        "Brothers",
        "Ssters",
        "Mystery",
        "Adventure",
        "Vintage",
        "Novel",
        "Hardcover",
        "e-book",
        "Brothers and sisters",
        "Country life",
        "Seashore",
        "Twins, fiction",
        "Children's fiction",
        "Bobbsey twins (fictitious characters), fiction",
        "Juvenile fiction",
        "Bobbsey Twins (Fictitious characters)",
        "Fiction, general",
        "Brothers and sisters, fiction",
      ],
      ia_collection: [
        "americana",
        "inlibrary",
        "internetarchivebooks",
        "printdisabled",
        "trent_university",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL20523216M",
      lending_identifier: "bobbseytwinsorm00hopegoog",
      authors: [
        {
          key: "/authors/OL761501A",
          name: "Laura Lee Hope",
        },
      ],
      first_publish_year: 1904,
      ia: "bobbseytwinsorm00hopegoog",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "bobbseytwinsorm00hopegoog",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL4072567W",
        openlibrary_edition: "OL20523216M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL278437W",
      title: "La sombra del viento",
      edition_count: 93,
      cover_id: 10107644,
      cover_edition_key: "OL23038029M",
      subject: [
        "Mothers and sons",
        "Verschollenheit",
        "Widowers",
        "Fiction",
        "Autor",
        "Books",
        "Buch",
        "Young men",
        "Faszination",
        "Rare books",
        "Junge",
        "Antiquarian booksellers",
        "Antiquarian booksellers in fiction",
        "Books in fiction",
        "Rare books in fiction",
        "Young men in fiction",
        "Mothers and sons in fiction",
        "Widowers in fiction",
        "novel",
        "Roman",
        "Literary fiction",
        "Spanish: Adult Fiction",
        "Detective and mystery stories",
        "out-of-print books",
        "Spanish novelists",
        "Novela de misterio",
        "Viudos",
        "Libros raros",
        "Madres e hijos",
        "Jóvenes (Hombres)",
        "Ficción",
        "Libros",
        "Libreros anticuarios",
        "Spanish fiction",
        "Fiction, suspense",
        "Authors, fiction",
        "Barcelona (spain), fiction",
        "Booksellers and bookselling, fiction",
        "Noveller",
        "Mystery fiction",
        "Books and reading",
        "Social conditions",
        "nyt:trade-fiction-paperback=2009-07-12",
        "New York Times bestseller",
        "Fiction, thrillers, suspense",
        "Fortellinger",
        "Forteljingar",
        "Fiction, thrillers, general",
        "Spanish Detective and mystery stories",
        "Jeunes hommes",
        "Romans, nouvelles",
        "Livres rares",
      ],
      ia_collection: [
        "americana",
        "americanuniversity-ol",
        "china",
        "cnusd-ol",
        "cua-ol",
        "dartmouthlibrary-ol",
        "delawarecountydistrictlibrary",
        "delawarecountydistrictlibrary-ol",
        "denverpubliclibrary-ol",
        "drakeuniversity-ol",
        "goffstownlibrary-ol",
        "hamiltonpubliclibrary-ol",
        "inlibrary",
        "internetarchivebooks",
        "ithacacollege-ol",
        "johnshopkins-ol",
        "kalamazoocollege-ol",
        "library_of_atlantis",
        "miltonpubliclibrary-ol",
        "occidentalcollegelibrary-ol",
        "openlibrary-d-ol",
        "printdisabled",
        "riceuniversity-ol",
        "rochester-ol",
        "stmaryscountylibrary",
        "tulsacc-ol",
        "udc-ol",
        "uni-ol",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "wilsoncollege-ol",
        "worthingtonlibraries-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL32174489M",
      lending_identifier: "lombreduventroma0000ruiz",
      authors: [
        {
          key: "/authors/OL2632116A",
          name: "Carlos Ruiz Zafón",
        },
        {
          key: "/authors/OL8742033A",
          name: "Frédéric Meaux",
        },
        {
          key: "/authors/OL3112610A",
          name: "François Maspero",
        },
        {
          key: "/authors/OL9148044A",
          name: ". ResumenExpress",
        },
      ],
      first_publish_year: 2001,
      ia: "lombreduventroma0000ruiz",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "lombreduventroma0000ruiz",
        isbn: "2246631610",
        oclc: null,
        openlibrary_work: "OL278437W",
        openlibrary_edition: "OL32174489M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL45866W",
      title: "George's Marvelous Medicine",
      edition_count: 91,
      cover_id: 9298669,
      cover_edition_key: "OL16129660M",
      subject: [
        "Roald Dahl",
        "Quentin Blake",
        "Children",
        "Children's",
        "Kid's",
        "Juvenile",
        "Fiction",
        "Literature",
        "Stories",
        "Chapters",
        "Chapter Book",
        "Books",
        "Grandmothers",
        "Magic",
        "Potions",
        "Brews Formulas",
        "Juvenile fiction",
        "Behaviour",
        "Humorous stories",
        "Children's stories",
        "Children's fiction",
        "Children's humourous stories",
        "Medical fiction",
        "Magic, fiction",
        "Grandparents, fiction",
        "Grands-parents",
        "Romans",
        "Magie",
        "The Fantastic",
        "Fantastique",
        "Romans, nouvelles, etc. pour la jeunesse",
        "Spanish language materials",
        "Abuelas",
        "Ficcion juvenil",
        "Magia",
      ],
      ia_collection: [
        "americana",
        "bpljordan-ol",
        "china",
        "cnusd-ol",
        "delawarecountydistrictlibrary",
        "denverpubliclibrary-ol",
        "framingham-ol",
        "friendsofthesanfranciscopubliclibrary",
        "goffstownlibrary-ol",
        "hamiltonpubliclibrary-ol",
        "inlibrary",
        "internetarchivebooks",
        "library_of_atlantis",
        "miltonpubliclibrary-ol",
        "occidentalcollegelibrary-ol",
        "openlibrary-d-ol",
        "popularchinesebooks",
        "printdisabled",
        "unb-ol",
        "universityofarizona-ol",
        "universityofoklahoma-ol",
        "worthingtonlibraries-ol",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL32761614M",
      lending_identifier: "georgesmarvellou0000dahl_c8l4",
      authors: [
        {
          key: "/authors/OL34184A",
          name: "Roald Dahl",
        },
        {
          key: "/authors/OL236943A",
          name: "Quentin Blake",
        },
      ],
      first_publish_year: 1981,
      ia: "georgesmarvellou0000dahl_c8l4",
      public_scan: false,
      has_fulltext: true,
      availability: {
        status: "borrow_available",
        available_to_browse: true,
        available_to_borrow: true,
        available_to_waitlist: false,
        is_printdisabled: true,
        is_readable: false,
        is_lendable: true,
        is_previewable: true,
        identifier: "georgesmarvellou0000dahl_c8l4",
        isbn: "0224019015",
        oclc: null,
        openlibrary_work: "OL45866W",
        openlibrary_edition: "OL32761614M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: true,
        is_browseable: true,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL14877434W",
      title: "The plays of Oscar Wilde",
      edition_count: 84,
      cover_id: 6984380,
      cover_edition_key: "OL6496989M",
      subject: [
        "Books",
        "Correspondence",
        "Criticism",
        "English language",
        "English literature",
        "History and criticism",
        "Irish authors",
        "Literature",
        "Quotations",
        "Readers",
        "Reviews",
        "Textbooks for foreign speakers",
        "Theory",
        "Translations into Russian",
        "Critique et interprétation",
        "Literaturkritik",
        "English drama",
        "English poetry",
        "Industrial relations",
        "Long Now Manual for Civilization",
        "Drama",
        "Anthologies",
        "Dramatic works",
        "Criticism and interpretation",
        "Poetic works",
        "Literatura inglesa",
        "English wit and humor",
        "Teatro",
        "Poesia",
        "Social life and customs",
        "Manners and customs",
        "British and irish fiction (fictional works by one author)",
        "British and irish drama (dramatic works by one author)",
        "Collected works (single author, multi-form)",
        "Wilde, oscar, 1854-1900",
        "English Historical drama",
        "Saint Bartholomew's Day, Massacre of, France, 1572",
        "Jews",
        "Irish Authors",
        "Biography",
        "Correspondence (Wilde, Oscar)",
        "Authors, irish",
        "Poetry (poetic works by one author)",
        "Littérature anglaise",
        "English language, textbooks for foreign speakers",
      ],
      ia_collection: [
        "americana",
        "belmont-ol",
        "binghamton-ol",
        "china",
        "cnusd-ol",
        "cua-ol",
        "dartmouthlibrary-ol",
        "drakeuniversity-ol",
        "gwulibraries-ol",
        "inlibrary",
        "internetarchivebooks",
        "ithacacollege-ol",
        "johnshopkins-ol",
        "occidentalcollegelibrary-ol",
        "openlibrary-d-ol",
        "printdisabled",
        "riceuniversity-ol",
        "rochester-ol",
        "rutgersuniversitylibraries",
        "schroederlibrary-ol",
        "the-claremont-colleges-ol",
        "trent_university",
        "tulsacc-ol",
        "udc-ol",
        "unb-ol",
        "uni-ol",
        "universityofarizona-ol",
        "universityofcoloradoboulder-ol",
        "universityofoklahoma-ol",
        "uslprototype",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL6965952M",
      lending_identifier: "playsofoscarwild01wild",
      authors: [
        {
          key: "/authors/OL20646A",
          name: "Oscar Wilde",
        },
      ],
      first_publish_year: 1900,
      ia: "playsofoscarwild01wild",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "playsofoscarwild01wild",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL14877434W",
        openlibrary_edition: "OL6965952M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
    {
      key: "/works/OL942666W",
      title: "Tartarin de Tarascon",
      edition_count: 83,
      cover_id: 8243923,
      cover_edition_key: "OL23300685M",
      subject: [
        "French language",
        "Readers",
        "Book design",
        "Books",
        "Illustration of",
      ],
      ia_collection: [
        "additional_collections",
        "americana",
        "cdl",
        "cornell",
        "inlibrary",
        "internetarchivebooks",
        "kellylibrary",
        "microfilm",
        "printdisabled",
        "robarts",
        "sablecentre",
        "toronto",
        "university_of_alberta_libraries",
        "university_of_alberta_libraries_microfilm",
        "universityofottawa",
        "worksintranslation",
      ],
      lendinglibrary: false,
      printdisabled: true,
      lending_edition: "OL23161095M",
      lending_identifier: "aventuresprodigi00daud",
      authors: [
        {
          key: "/authors/OL83503A",
          name: "Alphonse Daudet",
        },
      ],
      first_publish_year: 1800,
      ia: "aventuresprodigi00daud",
      public_scan: true,
      has_fulltext: true,
      availability: {
        status: "open",
        available_to_browse: false,
        available_to_borrow: false,
        available_to_waitlist: false,
        is_printdisabled: false,
        is_readable: true,
        is_lendable: false,
        is_previewable: true,
        identifier: "aventuresprodigi00daud",
        isbn: null,
        oclc: null,
        openlibrary_work: "OL942666W",
        openlibrary_edition: "OL23161095M",
        last_loan_date: null,
        num_waitlist: null,
        last_waitlist_date: null,
        is_restricted: false,
        is_browseable: false,
        __src__: "core.models.lending.get_availability",
      },
    },
  ];
  
  return (
    <div className="table-container">
      {/* {subject} */}
      <table>
        <tbody>
          <tr>
            <th>Title and Sub Title</th>
            <th>Author</th>
            <th>First Publish Year</th>
          </tr>
          {booksData.map((book) => {
            return (
              <tr key={book.key}>
                <td>{book.title}</td>
                <td>{book.authors.map((author, index) => index === 0 ? `${author.name}` : `, ${author.name}`)}</td>
                <td>{book.first_publish_year}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

export default Books;
